all:
  hosts:
    server1:
      ansible_host: pdns.uat.local.ca
      ansible_user: vagrant 
      ansible_ssh_pass: vagrant
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'